name: todo
repository: https://github.com/JLogical-Apps/flood-example

packages:
  - todo
  - todo_core

command:
  bootstrap:
    usePubspecOverrides: true
scripts:
  test:
    name: test
    description: 'Run all tests'
    run: |
      melos exec --fail-fast                                  -- flutter analyze . && \
      melos exec --fail-fast --dir-exists="test" --no-flutter -- flutter test . && \
      melos exec --fail-fast --dir-exists="test" --flutter    -- flutter test .