name: flood_todo
description: Example Todo app with authentication using Flood.

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

version: 0.0.1

dependencies:
  lints: ^2.0.0

dev_dependencies:
  melos: ^3.1.1