name: todo
description: Example Flutter app using JLogical Utils.
publish_to: none
version: 0.0.11+41
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  jlogical_utils:
    git:
      url: "git@github.com:jaboyc/jlogical_utils.git"
      ref: v3.2
      path: packages/jlogical_utils/jlogical_utils
  todo_core:
    path: ../todo_core
flutter:
  uses-material-design: true
  assets:
    - assets/
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.3.7
dependency_overrides:
  intl: 0.18.0
  win32: 4.1.0
  path: 1.8.3
  js: 0.6.5
  posix: 5.0.0
